#!/bin/bash
#
# 	  mp3tffn - mp3 tags from file name
#     Copyright (C) 2014  Marco Benzi
#
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.

if [[ $# != 2 ]]; then
  echo Usage: $0 [artist] [album name]
  exit
fi

ls *.mp3 > $$

while read file; do
  tmp=${file##*-}
  trackName=${tmp%%.*}
  trackNum=${file%%-*}
  id3tag --artist="$1" --album="$2" --song="$trackName" --track="$trackNum" "$file"
done < $$

rm $$
